apiVersion: v1
kind: Service
metadata:
  name: load-service
spec:
  selector:
    app: load-service
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-service
spec:
  selector:
    matchLabels:
      app: load-service
  replicas: 1
  template:
    metadata:
      labels:
        app: load-service
    spec:
      containers:
      - name: load-service
        image: load-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081